name: Coverage.Py
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: make docker-build
    - name: coverage.py badge
      # You may pin to the exact commit or the version.
      # uses: tj-actions/coverage-badge-py@786077b81572723a796adaf34015dfaeea425c3b
      uses: tj-actions/coverage-badge-py@v1.6
